export const DANH_MUC_BANG_GIA: Record<
  string,
  { name: string; symbols: Array<string> }
> = {
  vn30: {
    name: "VN30",
    symbols: [
      "ACB",
      "BCM",
      "BID",
      "BVH",
      "CTG",
      "FPT",
      "GAS",
      "GVR",
      "HDB",
      "HPG",
      "MBB",
      "MSN",
      "MWG",
      "PLX",
      "POW",
      "SAB",
      "SHB",
      "SSB",
      "SSI",
      "STB",
      "TCB",
      "TPB",
      "VCB",
      "VHM",
      "VIB",
      "VIC",
      "VJC",
      "VNM",
      "VPB",
      "VRE",
    ],
  },
  batdongsan: {
    name: "Bất động sản",
    symbols: [
      "PDR",
      "DXS",
      "TCH",
      "DXG",
      "NTL",
      "KDH",
      "HDG",
      "HLD",
      "HHS",
      "SCR",
      "KHG",
      "NLG",
      "HDC",
      "HUT",
      "DIG",
      "CEO",
      "IJC",
      "HTN",
      "ITA",
      "VHM",
      "BCR",
      "BCM",
      "KBC",
      "CRE",
      "VIC",
      "HQC",
      "VRE",
      "QCG",
      "NVL",
    ],
  },
  chungkhoan: {
    name: "Chứng khoán",
    symbols: [
      "ORS",
      "BVS",
      "FTS",
      "CTS",
      "HCM",
      "VCI",
      "VDS",
      "BSI",
      "MBS",
      "SSI",
      "AGR",
      "VND",
      "TVS",
      "AAS",
      "SBS",
      "APS",
      "EVS",
      "PSI",
      "SHS",
      "TCI",
      "VIG",
      "VIX",
      "DSE",
      "TVB",
      "APG",
      "WSS",
      "DSC",
    ],
  },
  nganhang: {
    name: "Ngân hàng",
    symbols: [
      "EVF",
      "TCB",
      "LPB",
      "MBB",
      "EIB",
      "SSB",
      "VCB",
      "CTG",
      "VIB",
      "BID",
      "HDB",
      "STB",
      "ACB",
      "BAB",
      "BVB",
      "SHB",
      "TPB",
      "MSB",
      "VAB",
      "OCB",
      "VPB",
      "NVB",
      "ABB",
      "NAB",
    ],
  },
  thep: {
    name: "Thép",
    symbols: [
      "SHI",
      "SMC",
      "NSH",
      "TLH",
      "VGS",
      "HSG",
      "HPG",
      "POM",
      "SHA",
      "NKG",
      "TVN",
      "VCA",
    ],
  },
  dauKhi: {
    name: "Dầu khí",
    symbols: [
      "PLC",
      "PVD",
      "PVS",
      "PVC",
      "PVP",
      "CNG",
      "PVT",
      "PXS",
      "PXT",
      "GAS",
      "PVB",
      "BSR",
      "PSH",
    ],
  },
  congNghe: {
    name: "Công nghệ",
    symbols: ["FPT", "CMG", "VGI", "VTP", "FOX", "FOC", "ITD", "CTR"],
  },
  dienNangLuong: {
    name: "Điện - Năng lượng",
    symbols: [
      "HDG",
      "POW",
      "HND",
      "KHP",
      "PPC",
      "PVG",
      "ΤΤΑ",
      "VNE",
      "GEG",
      "GEX",
      "NT2",
      "PC1",
      "QTP",
      "REE",
      "SJD",
      "TV2",
      "VSH",
    ],
  },
  hangKhongDuLich: {
    name: "Hàng không - Du lịch",
    symbols: [
      "ACV",
      "AST",
      "HVN",
      "SAS",
      "VJC",
      "VTD",
      "NCT",
      "DAH",
      "RIC",
      "SCS",
      "SGN",
      "SKG",
    ],
  },
  batDongSanKCN: {
    name: "Bất động sản KCN",
    symbols: [
      "GVR",
      "D2D",
      "IDC",
      "ITA",
      "LHG",
      "NTC",
      "PHR",
      "SIP",
      "SZC",
      "SZL",
      "TIP",
      "VGC",
      "DTD",
      "KBC",
    ],
  },
  baoHiem: {
    name: "Bảo hiểm",
    symbols: [
      "BIC",
      "BMI",
      "BVH",
      "MIG",
      "PGI",
      "PRE",
      "PTI",
      "PVI",
      "VNR",
      "ABI",
    ],
  },
  banLe: {
    name: "Bán lẻ",
    symbols: ["DGW", "PET", "PNJ", "FRT", "PSD", "MWG"],
  },
  nuocNhua: {
    name: "Nước - Nhựa",
    symbols: [
      "AAA",
      "APH",
      "BMP",
      "BWE",
      "DAG",
      "NTP",
      "TDM",
      "VNP",
      "HII",
      "NHH",
      "PGN",
      "PLP",
    ],
  },
  otoPhuTung: {
    name: "Ô tô - Phụ tùng",
    symbols: ["DRC", "HAX", "CTF", "CSM"],
  },
  hoaChatPhanBon: {
    name: "Hoá chất - Phân bón",
    symbols: ["BFC", "CSV", "DCM", "DDV", "DPM", "DGC", "LAS", "LIX", "PMB"],
  },
  duocYTe: {
    name: "Dược - Y tế",
    symbols: [
      "DBD",
      "DCL",
      "DHG",
      "DHT",
      "DMC",
      "IMP",
      "LDP",
      "SPM",
      "TNH",
      "AMV",
      "JVC",
    ],
  },
  cangBienVanTai: {
    name: "Cảng biển - Vận tải",
    symbols: [
      "PVP",
      "PVT",
      "HHG",
      "PHP",
      "SKG",
      "STG",
      "SWC",
      "TCL",
      "TMS",
      "VOS",
      "VSC",
      "VTO",
      "DVP",
      "DXP",
      "GMD",
      "GSP",
      "HAH",
      "ILB",
      "SGP",
      "TCO",
      "TCW",
      "VIP",
      "VNA",
    ],
  },
  detMay: {
    name: "Dệt may",
    symbols: ["ADS", "EVE", "GIL", "KMR", "MSH", "STK", "TCM", "TNG", "VGT"],
  },
  vlxd: {
    name: "VLXD",
    symbols: [
      "CTR",
      "HUT",
      "VGC",
      "LIG",
      "BCC",
      "BDT",
      "BOT",
      "BTS",
      "C4G",
      "CRC",
      "CTD",
      "CTI",
      "DHA",
      "G36",
      "HBC",
      "HVH",
      "LCG",
      "NED",
      "PHC",
      "PTB",
      "PXT",
      "SD6",
      "TTF",
      "VCS",
      "AMS",
      "BCE",
      "CIG",
      "CII",
      "DC4",
      "DVG",
      "FCM",
      "HHV",
      "HOM",
      "HT1",
      "L14",
      "L18",
      "NDX",
      "NHA",
      "S99",
      "SCI",
      "SDD",
      "TCD",
      "UDC",
      "VC2",
      "VC9",
      "VCG",
      "VLB",
      "VTV",
      "PC1",
      "DTD",
      "VNE",
      "BMP",
    ],
  },
  caoSu: {
    name: "Cao su",
    symbols: ["GVR", "DPR", "DRI", "TNC", "DRG", "HRC", "TRC", "PHR"],
  },
  thuySan: {
    name: "Thủy sản",
    symbols: ["AAM", "ACL", "ANV", "CMX", "FMC", "IDI", "VHC", "ASM"],
  },
  dauTuCong: {
    name: "Đầu tư công",
    symbols: [
      "TV2",
      "BCC",
      "BTS",
      "C4G",
      "CTI",
      "DHA",
      "G36",
      "KSB",
      "LCG",
      "SD6",
      "THG",
      "C32",
      "C47",
      "CII",
      "FCN",
      "HHV",
      "HOM",
      "HT1",
      "SD5",
      "TCD",
      "VCG",
    ],
  },
  thucPham: {
    name: "Thực phẩm",
    symbols: [
      "VNM",
      "AFX",
      "HAG",
      "KDC",
      "LSS",
      "LTG",
      "MCM",
      "MLS",
      "NAF",
      "QNS",
      "TAR",
      "VHE",
      "VLC",
      "APF",
      "BNA",
      "DBC",
      "PAN",
      "SLS",
      "VOC",
      "AIG",
      "MSN",
    ],
  },
  duongGo: {
    name: "Đường - Gỗ",
    symbols: ["TTF", "GDT", "LSS", "QNS", "SBT", "SLS"],
  },
};
