export const LOC_CO_PHIEU: Record<string, { name: string }> = {
  giaTriGiaoDichRong: {
    name: "Giá trị giao dịch ròng",
  },
  bienDoGiaDongCua: {
    name: "Biên độ giá đóng cửa",
  },
  pe: {
    name: "P/E",
  },
  vonhoa: {
    name: "Vốn hóa",
  },
  esp: {
    name: "EPS",
  },
};

export const TIEU_CHI_LOC = [
  {
    name: "Ngành",
    type: "select",
    options: [
      { label: "Ngân hàng" },
      { label: "Tài nguyên cơ bản" },
      { label: "Bán lẻ" },
      { label: "Bảo hiểm" },
      { label: "Bất động sản" },
      { label: "Công nghệ thông tin" },
      { label: "Viễn thông" },
      { label: "Du lịch và giải trí" },
      { label: "Dược phẩm và Y tế" },
      { label: "Dầu khí" },
      { label: "Dịch vụ tài chính" },
      { label: "Hàng & Dịch vụ công nghiệp" },
      { label: "Hàng cá nhân & Gia dụng" },
      { label: "Hoá chất" },
      { label: "Tiện ích cộng đồng" },
      { label: "Truyền thông" },
      { label: "Xây dựng và Vật liệu" },
      { label: "Ô tô và phụ tùng" },
    ],
  },
  {
    name: "KLGD so sánh với % KLTB(50 phiên)",
    type: "minmax",
    suggestions: [
      { label: "Dưới 30%" },
      { label: "Trên 30%" },
      { label: "Trên 50%" },
      { label: "Trên 100%" },
      { label: "Trên 150%" },
    ],
  },
  {
    name: "KL mua luỹ kế (5 phiên)",
    type: "minmax",
    suggestions: [
      { label: "Dưới 100K" },
      { label: "Trên 100K" },
      { label: "Trên 300K" },
      { label: "Trên 500K" },
      { label: "Trên 1000K" },
    ],
  },
  {
    name: "KL bán luỹ kế (5 phiên)",
    type: "minmax",
    suggestions: [
      { label: "Dưới 100K" },
      { label: "Trên 100K" },
      { label: "Trên 300K" },
      { label: "Trên 500K" },
      { label: "Trên 1000K" },
    ],
  },
  {
    name: "Xu hướng ngắn hạn",
    type: "select",
    options: [{ label: "Tăng" }, { label: "Giảm" }],
  },
  {
    name: "Xu hướng trung hạn",
    type: "select",
    options: [{ label: "Tăng" }, { label: "Giảm" }],
  },
  {
    name: "Xu hướng dài hạn",
    type: "select",
    options: [{ label: "Tăng" }, { label: "Giảm" }],
  },
  {
    name: "Sức mạnh",
    type: "select",
    options: [
      { label: "Tăng mạnh" },
      { label: "Tăng yếu" },
      { label: "Giảm mạnh" },
      { label: "Giảm yếu" },
    ],
  },
  {
    name: "RRG",
    type: "select",
    options: [
      { label: "Cải thiện" },
      { label: "Dẫn dắt" },
      { label: "Suy yếu" },
      { label: "Tụt hậu" },
    ],
  },
  {
    name: "RS",
    type: "minmax",
    suggestions: [
      { label: "Dưới 30" },
      { label: "Trên 30" },
      { label: "Trên 50" },
      { label: "Trên 70" },
    ],
  },
  {
    name: "Mẫu hình giảm giá",
    type: "select",
    options: [
      { label: "Dragon Walks" },
      { label: "Ascending Triangle" },
      { label: "Falling Wedge" },
      { label: "Up Channel" },
      { label: "Rectangle (Bullish breakout)" },
      { label: "Symmetrical Triangle" },
      { label: "Mark Minervini" },
    ],
  },
  {
    name: "Mẫu hình tăng giá",
    type: "select",
    options: [
      { label: "Descending Triangle" },
      { label: "Rising Wedge" },
      { label: "Down Channel" },
      { label: "Rectangle (Bearish breakout)" },
      { label: "Expanding Triangle" },
      { label: "Delphic" },
      { label: "Sniper" },
      { label: "X300" },
    ],
  },
  {
    name: "Nến tăng giá",
    type: "select",
    options: [
      { label: "3 Inside Up" },
      { label: "Hammer" },
      { label: "Harami Bullish" },
      { label: "Bullish Doji Star" },
      { label: "Dragonfly Doji" },
      { label: "Morning Doji Star" },
      { label: "Near Doji" },
      { label: "Meeting Lines Bullish" },
      { label: "Piercing Line" },
      { label: "Separating Lines Bullish" },
      { label: "Tweezer Bottom" },
      { label: "Inverted Hammer" },
      { label: "Homing Pigeon" },
      { label: "Tri-Star Bullish" },
    ],
  },
  {
    name: "Nến giảm giá",
    type: "select",
    options: [
      { label: "3 Black Crows" },
      { label: "3 Outside Down" },
      { label: "Bearish Engulfing" },
      { label: "Bearish Hammer" },
      { label: "Counter Attack Bearish" },
      { label: "Deliberation Bearish" },
      { label: "Doji Star Bearish" },
      { label: "Evening Doji Star" },
      { label: "Evening Star" },
      { label: "Hanging Man" },
      { label: "Harami Bearish" },
      { label: "Harami Cross Bearish" },
      { label: "In Neck Bearish" },
      { label: "On Neck Bearish" },
      { label: "Shooting Star" },
      { label: "Side by Side White Lines Bearish" },
      { label: "Tri-Star Bearish" },
      { label: "Tweezer Top" },
    ],
  },
  {
    name: "Vùng cung",
    type: "select",
    options: [
      { label: "Break" },
      { label: "Cận trên" },
      { label: "Đảo chiều" },
    ],
  },
  {
    name: "Vùng cầu",
    type: "select",
    options: [
      { label: "Break" },
      { label: "Cận trên" },
      { label: "Đảo chiều" },
    ],
  },
  {
    name: "Hỗ trợ",
    type: "select",
    options: [
      { label: "Break" },
      { label: "Cận trên" },
      { label: "Đảo chiều" },
    ],
  },
  {
    name: "Kháng cự",
    type: "select",
    options: [
      { label: "Break" },
      { label: "Cận trên" },
      { label: "Đảo chiều" },
    ],
  },
  {
    name: "Kênh dưới",
    type: "select",
    options: [
      { label: "Break" },
      { label: "Cận trên" },
      { label: "Đảo chiều" },
    ],
  },
  {
    name: "Kênh trên",
    type: "select",
    options: [
      { label: "Break" },
      { label: "Cận trên" },
      { label: "Đảo chiều" },
    ],
  },
  {
    name: "Giá (%) so với MA(20)",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn -30%" },
      { label: "Lớn lớn -30%" },
      { label: "Lớn hơn 0%" },
      { label: "Lớn hơn 30%" },
    ],
  },
  {
    name: "Giá (%) so với MA(50)",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn -30%" },
      { label: "Lớn lớn -30%" },
      { label: "Lớn hơn 0%" },
      { label: "Lớn hơn 30%" },
    ],
  },
  {
    name: "Giá (%) so với MA(100)",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn -30%" },
      { label: "Lớn lớn -30%" },
      { label: "Lớn hơn 0%" },
      { label: "Lớn hơn 30%" },
    ],
  },
  {
    name: "Giá (%) so với MA(200)",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn -30%" },
      { label: "Lớn lớn -30%" },
      { label: "Lớn hơn 0%" },
      { label: "Lớn hơn 30%" },
    ],
  },
  {
    name: "Giá (%) so với Đỉnh 52 tuần",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn -30%" },
      { label: "Lớn lớn -30%" },
      { label: "Lớn hơn 0%" },
      { label: "Lớn hơn 30%" },
    ],
  },
  {
    name: "Giá (%) so với Đáy 52 tuần",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn -30%" },
      { label: "Lớn lớn -30%" },
      { label: "Lớn hơn 0%" },
      { label: "Lớn hơn 30%" },
    ],
  },
  {
    name: "Action Score",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn 30" },
      { label: "Lớn hơn 30" },
      { label: "Lớn hơn 50" },
      { label: "Lớn hơn 70" },
    ],
  },
  {
    name: "Mô hình kinh doanh",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn 30" },
      { label: "Lớn hơn 30" },
      { label: "Lớn hơn 50" },
      { label: "Lớn hơn 70" },
    ],
  },
  {
    name: "Sức khỏe tài chính",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn 30" },
      { label: "Lớn hơn 30" },
      { label: "Lớn hơn 50" },
      { label: "Lớn hơn 70" },
    ],
  },
  {
    name: "Hiệu quả kinh doanh",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn 30" },
      { label: "Lớn hơn 30" },
      { label: "Lớn hơn 50" },
      { label: "Lớn hơn 70" },
    ],
  },
  {
    name: "Biên an toàn",
    type: "minmax",
    suggestions: [
      { label: "Nhỏ hơn -30%" },
      { label: "Lớn lớn -30%" },
      { label: "Lớn hơn 0%" },
      { label: "Lớn hơn 30%" },
    ],
  },
];
